[phases.build]
cmds = [
  "chmod +x frontend/pre-build-check.sh && frontend/pre-build-check.sh",
  "chmod +x build-frontend.sh && ./build-frontend.sh",
  "rm -rf backend/static",
  "cp -r frontend/build backend/static"
]

[phases.setup]
cmds = [
  "cd backend && pip install -r requirements.txt"
]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
