[phases.build]
cmds = [
  "chmod +x frontend/pre-build-check.sh && frontend/pre-build-check.sh",
  "cd frontend && REACT_APP_API_URL=$REACT_APP_API_URL REACT_APP_GOOGLE_MAPS_API_KEY=$REACT_APP_GOOGLE_MAPS_API_KEY npm install && npm run build",
  "rm -rf backend/static",
  "cp -r frontend/build backend/static"
]

[phases.setup]
cmds = [
  "cd backend && pip install -r requirements.txt"
]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
