[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

[env]
FLASK_ENV = "production"
# Note: REACT_APP variables must be set in Railway dashboard
# They are injected during build time, not runtime
# Required variables:
# - REACT_APP_API_URL
# - REACT_APP_GOOGLE_MAPS_API_KEY
# - CLOUDINARY_CLOUD_NAME
# - CLOUDINARY_API_KEY
# - CLOUDINARY_API_SECRET
